# Generated by Django 5.2.15 on 2026-06-16 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='業務名')),
                ('required_people_per_day', models.PositiveIntegerField(default=1, verbose_name='1日あたりの必要人数')),
                ('required_skill', models.CharField(blank=True, max_length=200, verbose_name='必要スキル')),
                ('memo', models.TextField(blank=True, verbose_name='備考')),
            ],
            options={
                'verbose_name': '業務',
                'verbose_name_plural': '業務一覧',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='スタッフ名')),
                ('role', models.CharField(choices=[('admin', '管理者'), ('staff', 'パートスタッフ')], default='staff', max_length=10, verbose_name='権限区分')),
                ('memo', models.TextField(blank=True, verbose_name='備考')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('available_tasks', models.ManyToManyField(blank=True, related_name='capable_staff', to='shifts.task', verbose_name='担当可能業務')),
            ],
            options={
                'verbose_name': 'スタッフ',
                'verbose_name_plural': 'スタッフ一覧',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('confirmed', '確定')], default='draft', max_length=20, verbose_name='ステータス')),
                ('memo', models.TextField(blank=True, verbose_name='備考')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shifts', to='shifts.staff', verbose_name='担当スタッフ')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='shifts.task', verbose_name='業務')),
            ],
            options={
                'verbose_name': 'シフト',
                'verbose_name_plural': 'シフト一覧',
                'ordering': ['date', 'task'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('reason', models.TextField(blank=True, verbose_name='理由')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認'), ('rejected', '却下')], default='pending', max_length=20, verbose_name='ステータス')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_requests', to='shifts.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '休み申請',
                'verbose_name_plural': '休み申請一覧',
                'ordering': ['-date'],
                'unique_together': {('staff', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UnavailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='勤務不可日')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to='shifts.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '勤務不可日',
                'verbose_name_plural': '勤務不可日一覧',
                'ordering': ['date'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
