# Generated by Django 5.2.15 on 2026-06-19 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='年')),
                ('month', models.PositiveIntegerField(verbose_name='月')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提出日時')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='shifts.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '希望提出',
                'verbose_name_plural': '希望提出一覧',
                'unique_together': {('staff', 'year', 'month')},
            },
        ),
    ]
