# Generated by Django 5.2.15 on 2026-06-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_availabilitysubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='年')),
                ('month', models.PositiveIntegerField(verbose_name='月')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('needs_update', models.BooleanField(default=False, verbose_name='更新が必要')),
            ],
            options={
                'verbose_name': 'シフト公開',
                'verbose_name_plural': 'シフト公開一覧',
                'unique_together': {('year', 'month')},
            },
        ),
    ]
